apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |  
    - rolearn: arn:aws:iam::257038783065:user/k8s-admin
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:
        - system:nodes
